### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by ai1361720220000** [thsno02/StarGANv2-VC#59]
hello , could you share the Chinese data trained model? I have tested the performance using the original pretrained weight of the author, but the results is not good as for Chinese input.

**Comment by thsno02** [comment]
Sorry, I can't offer the model though I really want to help. The original pre-trained model is based on the English corpus, it works in some scenarios if you use it for fun. 

If you wanna put it into practice formally, I highly recommend you train a model based on your own dataset despite training starGANv2 is time-consuming. It's noteworthy that the qualify of the dataset correlates with the model performance, and the dialect of the speaker will affect the model performance too.
